### ISSUE TITLE
Unbreak ScrutinizerCI

### ISSUE THREAD

**Issue by thiemowmde** [wmde/WikibaseInternalSerialization#47]
As far as I can tell a change in a component required by this one makes all test fail. Which one? How to fix? How to avoid this in the future?

**Comment by thiemowmde** [comment]
No problem on my local machine. Pinging @JeroenDeDauw and @tobijat.

**Comment by JeroenDeDauw** [comment]
Meh. Why is "infrastructure" not in the default tag list?

**Comment by Benestar** [comment]
This is fixed, isn't it?

**Comment by addshore** [comment]
I would say so
https://scrutinizer-ci.com/g/wmde/WikibaseInternalSerialization/inspections
